name: Fake Books API Tests

on:
  workflow_dispatch:
    inputs:
      test_url:
        type: string
        description: "Test environment URL"
        required: false
  workflow_call:
    inputs:
      test_url:
        type: string
        description: "Test environment URL"
        required: false
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write # needed to push to gh-pages branch

jobs:
  api-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install

      - name: Run API tests
        env:
          TEST_URL: ${{ secrets.TEST_URL }}
        run: npm run api-tests

      - name: Install gh-pages
        run: npm install --save-dev gh-pages

      - name: Deploy Playwright report to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
