name: Fake Books API Tests

on:
  workflow_dispatch:
    inputs:
      test_url:
        type: string
        description: "Test environment URL"
        required: false
  workflow_call:
    inputs:
      test_url:
        type: string
        description: "Test environment URL"
        required: false
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: write # needed to push to gh-pages branch

jobs:
  api-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2, 3, 4]
        shardTotal: [4]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install

      - name: Run API tests
        env:
          TEST_URL: ${{ secrets.TEST_URL }}
        run: npm run api-tests

      - name: Upload blob report to GitHub Actions Artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: merged-blob-report
          path: blob-report
          retention-days: 1
      

  merge-reports-and-deploy:
    if: ${{ !cancelled() }}
    needs: [api-tests]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci

    - name: Download blob reports from GitHub Actions Artifacts
      uses: actions/download-artifact@v4
      with:
        path: merged-blob-report
        pattern: downloaded-blob-report

    - name: Merge into HTML Report
      run: npx playwright merge-reports --reporter html ./downloaded-blob-report

    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./playwright-report

    - name: Write URL in summary
      run: echo "Test results are available at - https://${{ github.repository_owner }}.github.io/avenga-assignment/${{ github.run_number }}/" >> $GITHUB_STEP_SUMMARY
